/**
 * Materialize the corpus as real, loadable plugins.
 *
 * Every layer of this project has been verified on its own; nothing has ever
 * booted whole. This writes one plugin module per corpus package, registering
 * that package's real tool names through the real `ctx.tools` service, and
 * composes them onto a real shipped profile. What boots — or fails to — is then
 * the actual runtime, not a model of it.
 *
 * The plugins are synthetic in body and authentic in registrations. A real
 * plugin's business logic cannot make a registry throw; its registration set
 * can, and that is what the corpus records exactly. Two consequences worth
 * stating: contributions the scanner could not resolve statically are absent
 * here, so this exercises no more contention than the published data claims;
 * and nothing here reproduces a plugin's runtime behaviour, so a pass means
 * "the composition mounts", never "these plugins work".
 *
 * Usage: node e2e/generate.mjs <count> [outDir]
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DSH_ROOT, require_ } from '../paths.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = require_(DSH_ROOT, 'DSH_ROOT', 'read the shipped profile it composes onto')

const count = Number.parseInt(process.argv[2] ?? '400', 10)
const outDir = process.argv[3] ?? join(here, 'workspace')

/** A package name the loader and the filesystem both accept as one segment. */
const slug = name => name.replace(/^@/, '').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase()

const corpus = JSON.parse(readFileSync(join(here, 'corpus-tools.json'), 'utf8'))

// Contended packages first: a composition of packages that never collide would
// boot today and would prove nothing about the substrate.
const claimants = new Map()
for (const [pkg, tools] of Object.entries(corpus)) {
  for (const tool of tools) {
    if (!claimants.has(tool)) claimants.set(tool, [])
    claimants.get(tool).push(pkg)
  }
}
const contendedPkgs = new Set()
for (const [, pkgs] of claimants) if (pkgs.length > 1) for (const pkg of pkgs) contendedPkgs.add(pkg)

const ordered = [
  ...Object.keys(corpus).filter(p => contendedPkgs.has(p)),
  ...Object.keys(corpus).filter(p => !contendedPkgs.has(p)),
].slice(0, count)

rmSync(outDir, { recursive: true, force: true })
mkdirSync(join(outDir, 'plugins'), { recursive: true })

/** One plugin module: the package's real tool names, nothing else. */
const moduleFor = (pkg, tools) => `// generated from corpus record for ${pkg}
import { defineTool } from '@deepseek-ai/dsh-tools'

export const name = ${JSON.stringify(slug(pkg))}
export const inject = ['tools']

export function apply(ctx) {
${tools.map(tool => `  ctx.effect(() => ctx.tools.register(defineTool({
    name: ${JSON.stringify(tool)},
    description: ${JSON.stringify(`${tool} (corpus stand-in for ${pkg})`)},
    parameters: {},
    output: {
      schema: { type: 'string' },
      render: (_args, value) => [{ type: 'text', text: String(value) }],
    },
    execute: () => ${JSON.stringify(`${tool} from ${pkg}`)},
  })), ${JSON.stringify(`${slug(pkg)}: ${tool}`)})`).join('\n')}
}
`

const rows = []
let toolCount = 0
for (const pkg of ordered) {
  const tools = corpus[pkg]
  const id = slug(pkg)
  writeFileSync(join(outDir, 'plugins', `${id}.mjs`), moduleFor(pkg, tools))
  rows.push({ id, pkg, tools })
  toolCount += tools.length
}

// The composition: a real shipped profile plus every generated row.
const base = readFileSync(join(repoRoot, 'examples/headless-agent/cordis.yml'), 'utf8')
const relPlugins = relative(outDir, join(outDir, 'plugins')).split('\\').join('/')
const composed = `${base}
# --- ${rows.length} corpus packages, generated by e2e/generate.mjs ---
${rows.map(r => `- id: ${r.id}\n  name: ./${relPlugins}/${r.id}.mjs`).join('\n')}
`
writeFileSync(join(outDir, 'cordis.yml'), composed)
writeFileSync(join(outDir, 'rows.json'), JSON.stringify(rows, null, 0))

const contendedHere = new Map()
for (const r of rows) for (const t of r.tools) {
  if (!contendedHere.has(t)) contendedHere.set(t, [])
  contendedHere.get(t).push(r.pkg)
}
const collisions = [...contendedHere].filter(([, p]) => p.length > 1)

console.log(`\n生成 ${rows.length} 个插件 · ${toolCount} 次工具注册 · 写入 ${outDir}`)
console.log(`其中会撞名的工具 ${collisions.length} 个,牵涉 ${new Set(collisions.flatMap(([, p]) => p)).size} 个包`)
console.log(`最热: ${collisions.sort((a, b) => b[1].length - a[1].length).slice(0, 5).map(([t, p]) => `${t}(${p.length})`).join(' ')}\n`)
